add jacoco

diff --git a/.github/workflows/pipeline-micro-java.yml b/.github/workflows/pipeline-micro-java.yml
--- a/.github/workflows/pipeline-micro-java.yml
+++ b/.github/workflows/pipeline-micro-java.yml
@@ -25,4 +25,8 @@ jobs:
 
     - name: Check Code Coverage
       run: |
-        ls -ltrh
+        COVERAGE=$(grep -Po "(?<=<counter type=\"INSTRUCTION\" covered=\")[^\"]+" build/reports/jacoco/test/jacocoTestReport.xml")
+        if [ "$(echo "$COVERAGE >= 85" | bc -l)" -eq 0 ]; then
+          echo "Error: La cobertura de código es inferior al 85% (actual: $COVERAGE%)."
+          exit 1
+        fi
